# Generated by Django 3.2.8 on 2021-10-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='test-image', upload_to='images'),
            preserve_default=False,
        ),
    ]
